### ISSUE TITLE
Question: Can you get data for users logged in/registered via facebook

### ISSUE THREAD

**Issue by Ahrengot** [fabulator/endomondo#1]
Hey there,

Do you know if it's possible to use this API wrapper if a user has signed up to Endomondo via Facebook? In that case the user wouldn't have a password, right? So would it be impossible to log in at that point?

**Comment by fabulator** [comment]
Hello,

yes, that is right. But users can create a password in Endomondo settings - https://www.endomondo.com/settings/account
