### ISSUE TITLE
New workouts are created as "live"

### ISSUE THREAD

**Issue by mkosiedowski** [fabulator/endomondo#2]
I created a workout as described in README and it was "live" in Endomondo. I managed to create finished workout using following code:
```php
$id = $endomondo->workouts->create(
    \Fabulator\Endomondo\Endomondo::SPORT_CYCLING_TRANSPORT,
    $date,
    $duration
    $distance
);
$endomondo->getOldAPI()->editWorkout(
    $id,
    ['end_time' => gmdate("Y-m-d H:i:s \U\T\C", $endDate->format("U"))]
);
```
This can be easily solved on API level by adding `end_time` in `EndomondoOld::createWorkout` in table `$set` defined in line `298`

**Comment by fabulator** [comment]
Thanks for reporting and solution. New workouts are no longer live in version v2.0.1
