### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by psukys** [fabulator/endomondo#3]
Logging in fails. By the looks of it, it seems that now login cannot be done by a simple "email", "password" POST request, but also needs a CSRF token.

Return error when trying a simple POST request on /rest/session:
```
"errors":[{"message":"CSRF prevention","code":3,"type":4}]} 
```

**Comment by fabulator** [comment]
Hello,

I'm no longer maintaing this repository. I was rewriting code to some new libraries - https://github.com/fabulator/endomondo https://github.com/fabulator/endomondo-api In this new project authorization works for me.
